apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal-kubernetes
  description: teste cluster devportal
  tags:
    - go
  annotations:
    backstage.io/kubernetes-id: "devportal-petclinic"
    veecode/cluster-name: "devportal-kubernetes"
    eks/region: "nyc3"
spec:
  type: service
  lifecycle: production
  owner: guest
  dependsOn: 
    - component:default/devportal-enviroment

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal-enviroment
  description: teste enviroment devportal
  annotations:
    backstage.io/kubernetes-id: "devportal-petclinic"
    veecode/cluster-name: "devportal-kubernetes"
    eks/region: "nyc3"
spec:
  type: service
  lifecycle: production
  owner: guest
  dependencyOf: 
    - component:default/devportal-kubernetes
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eks-br"
  environment:
    domain: 'apps.vkpr.net'
  annotations:
    github.com/project-slug: veecode-homolog/eks-br
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
    veecode/cluster-name: "eks-br"
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
