apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal-kubernetes
  description: teste cluster devportal
  tags:
    - go
  annotations:
    backstage.io/kubernetes-id: "devportal-petclinic"
    veecode/cluster-name: "devportal-kubernetes"
    eks/region: "nyc3"
spec:
  type: service
  lifecycle: production
  owner: guest
