apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: devportal-kubernetes-teste-luccas
  description: teste cluster devportal
  tags:
    - go
  annotations:
    backstage.io/kubernetes-id: "devportal-petclinic"
    veecode/cluster-name: "devportal-kubernetes"
    eks/region: "nyc3"
spec:
  lifecycle: production
  owner: group:default/admin
  dependsOn: 
    - enviroment:default/devportal-enviroment-teste-luccas
    - component:default/k3d-k3s-luccas
    - component:default/teste-component-luccas

---

apiVersion: backstage.io/v1alpha1
kind: Enviroment
metadata:
  name: devportal-enviroment-teste-luccas
  description: teste enviroment devportal
  annotations:
    backstage.io/kubernetes-id: "devportal-petclinic"
    veecode/cluster-name: "devportal-kubernetes"
    eks/region: "nyc3"
spec:
  lifecycle: production
  owner: group:default/admin
  dependencyOf: 
    - component:default/devportal-kubernetes
    
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "k3d-k3s-luccas"
  environment:
    domain: 'apps.vkpr.net'
  annotations:
    backstage.io/techdocs-ref: dir:.
    veecode/cluster-name: "k3d-k3s"
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/admin"
  ---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "teste-component-luccas"
  environment:
    domain: 'apps.vkpr.net'
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/admin"
