apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal
  description: teste cluster devportal
  tags:
    - go
  annotations:
    backstage.io/kubernetes-id: "devportal-petclinic"
spec:
  type: service
  lifecycle: production
  owner: guest
